name: Run SMA Bot and Send Telegram Alerts

on:
  workflow_dispatch:    # allows manual run
  schedule:
    - cron: '0 * * * *'  # runs every hour

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install yfinance pandas matplotlib python-telegram-bot

    - name: Run SMA Bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python3 sma_bot.py
